sudo: false

language: python
python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
    - gfortran
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libgmp-dev
    - libmpfr-dev
    - libglpk-dev

before_install:
  - curl -sO https://repo.continuum.io/miniconda/Miniconda2-4.0.5-Linux-x86_64.sh
    && echo 'ada5b7942e519829bc5e8e638d525e009676a7a598cf3dd80f041f6d5e39ddbb  Miniconda2-4.0.5-Linux-x86_64.sh'
    | shasum -a 256 -c -
  - bash Miniconda2-4.0.5-Linux-x86_64.sh -b -p ${HOME}/miniconda
  - source ${HOME}/miniconda/bin/activate root
  - conda update -q -y --all
  - conda install -q -y nomkl
  - conda install -q -y numpy scipy
  - conda info -a
  - pip install --ignore-installed --upgrade pip setuptools
  - pip install matplotlib
  - pip install nose

install:
  - python setup.py sdist
  - pip install dist/polytope-*.tar.gz

script:
  - ./run_tests.py --outofsource
  - curl -sO http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.4.tar.gz
    && echo '698b5c455645bb1ad29a185f0d52025f3bd7cb7261e182c8878b0eb60567a714  SuiteSparse-4.5.4.tar.gz'
    | shasum -a 256 -c -
  - tar -xzf SuiteSparse-4.5.4.tar.gz
  - export CVXOPT_SUITESPARSE_SRC_DIR=`pwd`/SuiteSparse
  - export CVXOPT_BUILD_GLPK=1
  - pip install cvxopt
  - python -c "import cvxopt.glpk"
  - ./run_tests.py --outofsource

notifications:
  email: false
