sudo: false

language: python
python:
  - "2.7_with_system_site_packages"

addons:
  apt:
    packages:
    - gfortran
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libgmp-dev
    - libmpfr-dev
    - python-numpy

before_install:
  - travis_wait 30 pip install scipy
  - pip install matplotlib
  - pip install nose

install:
  - pip install .

script: ./run_tests.py

notifications:
  email: false

